apiVersion: v1
kind: ConfigMap
metadata:
  name: private-frontend-configurations
  namespace: default
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "someconfigurationkey":"Hello World"
    }