name: Image Build for SampleAPI

on:
  push:
    branches: [ master ]
    paths:
    - SampleAPI/**
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: k8simagesregistery.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build ./SampleAPI --file SampleAPI/Dockerfile -t k8simagesregistery.azurecr.io/sampleapi:${{ github.sha }}
        docker push k8simagesregistery.azurecr.io/sampleapi:${{ github.sha }}


